server:
  port: 9000

spring:
  #指定当前的环境------在pom文件中取值使用@profiles.active@
  profiles:
    active: @profiles.active@
  application:
    name: springcloud-employee-consume  # 应用名称，注册到服务中心

#日志配置文件位置
logging:
  config: classpath:log4j/${spring.profiles.active}/log4j2.xml

#eureka服务中心的位置，作为客户端用于发现和注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/