server:
  port: 8001

spring:
  #指定当前的环境------在pom文件中取值使用@profiles.active@
  profiles:
    active: @profiles.active@
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-provide-8001?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: springcloud-employee-provider  # 应用名称，注册到服务中心（集群情况下名称一致）

#日志配置文件位置
logging:
  config: classpath:log4j/${spring.profiles.active}/log4j2.xml
  #开启打印sql
  level:
    com.fei.springcloudprovide8001.data.mapper: debug

#mybatis的mapper，xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml

#eureka服务中心的位置，作为客户端用于发现和注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ , http://feiyu:7001/eureka/

#监控的info信息
info:
  application.name: springcloud-provide-8001
  build.groupId: @project.groupId@
  build.artifactId: @project.artifactId@
  build.version: @project.version@