server:
  port: 4000

spring:
  #指定当前的环境------在pom文件中取值使用@profiles.active@
  profiles:
    active: @profiles.active@
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoshijiu333/springcloud-config.git   # config服务端配置，连接git（使用http形式加密码）
          username: xiaoshijiu333
          password: wangfei12128

#日志配置文件位置
logging:
  config: classpath:log4j/${spring.profiles.active}/log4j2.xml

# 注册到Eureka中
eureka:
  instance:
    instance-id: ${info.application.name}
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/,http://feiyu:7001/eureka/


#监控的info信息
info:
  application.name: springcloud-config-server
  build.groupId: @project.groupId@
  build.artifactId: @project.artifactId@
  build.version: @project.version@
