server:
  port: 9000

spring:
  #指定当前的环境------在pom文件中取值使用@profiles.active@
  profiles:
    active: @profiles.active@
  application:
    name: springcloud-employee-client-feign  # 应用名称，注册到服务中心

#日志配置文件位置
logging:
  config: classpath:log4j/${spring.profiles.active}/log4j2.xml

#eureka服务中心的位置，作为客户端用于发现和注册服务
eureka:
  client:
    register-with-eureka: false  #表示不向注册中心注册自己（消费者不需要注册自己）
    service-url:
      defaultZone: http://localhost:7000/eureka/ , http://feiyu:7001/eureka/

# 开启feign对hytrix的支持
feign:
  hystrix:
    enabled: true

# hystrix超时时间配置
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000